services:

  rdbms:
    image: docker.io/postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

  microservice:
    image: ghcr.io/chiroito/sample-microservice:main
    ports:
      - 8082:8080

# 開発環境ではセッションを外部に保存しない

volumes:
  pgdata: