networks:
  mynetwork:
    driver: bridge

services:

  app:
    image: localhost/cloud-native-monolith:latest
    restart: always
    ports:
      - 8080:8080
      - 9990:9990
      - 8443:8443
    environment:
      POSTGRESQL_DATABASE: user
      POSTGRESQL_USER: user
      POSTGRESQL_PASSWORD: pw
      POSTGRESQL_SERVICE_HOST: rdbms
      POSTGRESQL_SERVICE_PORT: 5432
      MICROSERVICE_HOSTNAME: microservice:8080
      SESSIONSTORE_HOST: sessionstore
      SESSIONSTORE_PORT: 11222
      SESSIONSTORE_USER: web-session-user
      SESSIONSTORE_PASSWORD: password
    volumes:
      - applog:/opt/eap/standalone/log
    networks:
      - mynetwork
    depends_on:
      sessionstore:
        condition: service_healthy


  rdbms:
    image: docker.io/postgres:16
    restart: always
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  microservice:
    image: ghcr.io/chiroito/sample-microservice:main
    restart: always
#    ports:
#      - 8082:8080
    networks:
      - mynetwork

  sessionstore:
    image: registry.redhat.io/datagrid/datagrid-8-rhel9:1.5-8.5.0.GA
    # https://catalog.redhat.com/software/containers/datagrid/datagrid-8-rhel9/62a80c58e265aa868784fdc8
    ports:
      - 11222:11222
#      - 11221:11221
#      - 2157:2157
#      - 45700:45700
#      - 57600:57600
#      - 7800:7800
    environment:
      USER: web-session-user
      PASS: password
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11222" ]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  pgdata:
  applog: