apiVersion: "v1"
kind: "ImageStream"
metadata:
  name: "cloud-native-monolith"
  namespace: "cloud-native-monolith"
spec:
  dockerImageRepository: "localhost/cloud-native-monolith/cloud-native-monolith"